wip

diff --git a/.github/workflows/print-github-pages-url.yml b/.github/workflows/print-github-pages-url.yml
--- a/.github/workflows/print-github-pages-url.yml
+++ b/.github/workflows/print-github-pages-url.yml
@@ -15,6 +15,14 @@ jobs:
         id: step_1
         run: |
           echo PAGES_URL=$(curl -s -H 'Accept: application/vnd.github+json' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pages | jq '.html_url') >> $GITHUB_ENV
-      - name: Stop if null
+      - name: Quit if GitHub pages is null
         if: ${{ env.PAGES_URL }} == null
-        run: echo "::error ::Could not retrieve GitHub pages URL"
+        uses: actions/github-script@v3
+        with:
+          script: |
+            core.setFailed('Could not retrieve GitHub pages URL.')        
+
+
+        # run: |
+        #   echo "::error ::Could not retrieve GitHub pages URL"
+        #   exit 1
